### ISSUE TITLE
Test LA dataset

### ISSUE THREAD

**Issue by smanman** [himashi92/Co-BioNet#11]
Hello, I'm using eval_3d_ensamble.py to test LA dataset, I get error as below image, I set the condition --dataset_name LA --labelnum 8,what's the problem please?
![Uploading LA.png…]()

**Comment by himashi92** [comment]
Hello, can you re-upload the error screenshot? Thanks

**Comment by smanman** [comment]
ok！
![LA](https://github.com/himashi92/Co-BioNet/assets/50786422/a745b839-c4f8-4e72-aca1-1d7d33fcdae8)
 报错代码：
ssh://smm@210.45.212.240:22/home/sys123456/yes/envs/venv/bin/python3.8 -u /home/smm/code/Co-BioNet-main/code/eval_3d_ensemble.py --dataset_name LA --labelnum 8
/home/smm/code/Co-BioNet-main/model/LA_Co_BioNet_8_labeled/vnet_predictions_ensemble/test
init weight from /home/smm/code/Co-BioNet-main/model/LA_Co_BioNet_8_labeled/vnet/best_model_1.pth
init weight from /home/smm/code/Co-BioNet-main/model/LA_Co_BioNet_8_labeled/vnet/best_model_2.pth
00,	0.00867, 0.00436, 89.14034, 2.26908
01,	0.01103, 0.00555, 93.55747, 4.30744
02,	0.90351, 0.82401, 8.66025, 1.03180
03,	0.90367, 0.82427, 5.74456, 1.45423
04,	0.89410, 0.80848, 4.47214, 1.20308
Traceback (most recent call last):
  File "/home/smm/code/Co-BioNet-main/code/eval_3d_ensemble.py", line 74, in <module>
    metric = calculate_metric()
  File "/home/smm/code/Co-BioNet-main/code/eval_3d_ensemble.py", line 60, in calculate_metric
    avg_metric = test_all_case(FLAGS.model, 1, net_1, net_2, image_list, num_classes=num_classes,
  File "/home/smm/code/Co-BioNet-main/code/utils/test_patch_ensemble.py", line 68, in test_all_case
    prediction = getLargestCC(prediction)
  File "/home/smm/code/Co-BioNet-main/code/utils/test_patch_ensemble.py", line 14, in getLargestCC
    assert (labels.max() != 0)  # assume at least 1 CC
AssertionError

**Comment by himashi92** [comment]
Can you remove or comment line 14 and rerun the script?

**Comment by smanman** [comment]
After removing it, it still reports an error, can you provide the steps and code to test the LA dataset, please!

**Comment by smanman** [comment]
I changed the function to:
def getLargestCC(segmentation):#LA
    labels = label(segmentation)
    if labels.max() == 0.
        print("No connected components found in the segmentation.")
        return segmentation
    largestCC = labels == np.argmax(np.bincount(labels.flat)[1:]) + 1
    return largestCC, reproduce 10% with labels LA test result is: [dice,jc,hd,asd] [ 0.60614098 0.5435772 25.03224786 2.27713335], please ask to change to the above function is correct, this result deviation is big?

**Comment by himashi92** [comment]
Did you use the given pretrained weights or train the model yourself? It seems the model is not trained enough, which causes the error. Could you please try downloading pretrained weights and see whether you are getting the same error?

**Comment by smanman** [comment]
I trained the model myself with 15000 iterations, how many times did you train the LA dataset? I will try to use the pre-training weights you guys gave me later, thanks a lot!

**Comment by smanman** [comment]
@himashi92 
Hello, could you please provide the hyperparameters for training the LA dataset? I noticed a significant difference in dice accuracy between my reproduction using 10% labeled LA data (60.61) and the accuracy reported in your paper (89.2). Thank you very much for your assistance!

**Comment by himashi92** [comment]
Hello, these are the hyper-parameters: 
train_cobionet_semi.py --dataset_name LA --labelnum 8 --lamda 0.7 --consistency 1.0 --mu 0.01 --t_m 0.4 --max_iteration 15000

**Comment by smanman** [comment]
@himashi92 
Thank you very much for your reply! I used the same parameters as yours and the results were way too low. I listened to the advice you gave increasing the number of iterations to 30,000, training twice as much as before, and still dice accuracy is over sixty, if I use the pre-training weights file you provided, do I just need to put the file under the code/model folder? Do I need to do anything else?

**Comment by himashi92** [comment]
It's strange because the results on my machine are reproducible. What GPU do you use? Did you use the exact batch sizes as well?
Put the pre-trained weights under the model folder and can you run inference?

**Comment by smanman** [comment]
@himashi92 
I am using a 3090 server and the training batch size has not been modified to match your source code.

**Comment by smanman** [comment]
@himashi92 
Hi author, I tested the dataset directly on the data using the pre-training weights file you provided, and the result is the same as the one you provided in your paper, I plotted the trend of my own reproduced loss values, and it didn't converge, what's the size of the batch size when you train the LA dataset using A40? I provided a default value of 2. Is it possible that the training did not converge due to the different server types and the hyperparameters you provided are no longer valid? Here is my loss trend graph.
![LA_loss](https://github.com/himashi92/Co-BioNet/assets/50786422/1742c4ae-c23c-4a7c-829e-48459df331ab)

**Comment by himashi92** [comment]
Hi, I tried running with the given parameters on 3090, and I am getting a memory error. I ran all experiments in A40 GPU. Did you use these settings as it is with labeled_bs=2 and batch_size=4?

**Comment by smanman** [comment]
@himashi92 
I'm using labeled_bs=1and batch_size=2 on the 3090.

**Comment by smanman** [comment]
@himashi92 

I understand where the problem is now. If I adjust labeled_bs=2 and batch_size=4 to labeled_bs=1 and batch_size=2, and increase the number of training iterations from the original 15000 to 100000, will this significantly affect the results?

**Comment by himashi92** [comment]
Hello, I haven't tried that hyper-parameter setting. But I can say these types of neural networks are significantly hyper-parameter-sensitive.

**Comment by smanman** [comment]
@himashi92 
"I set the number of iterations to 100,000, but the accuracy results are still very low, and I encountered the previous error again. I don't know where the problem lies. Your code provides the LA and Pancreas_CT datasets. Do I need to preprocess them before training? Does the MSD dataset also require preprocessing?

**Comment by himashi92** [comment]
You do not need to preprocess them. As I mentioned, you must use the exact batch sizes mentioned in the repository and the paper to reproduce the results, as these co-training networks are susceptible to batch sizes.  If you could train in A40 GPU, you can reproduce the results.

**Comment by smanman** [comment]
@himashi92 
Tnank you very much!
