### ISSUE TITLE
Other data sets(ACDC)

### ISSUE THREAD

**Issue by smanman** [himashi92/Co-BioNet#12]
Hello Author! Have you used the ACDC dataset before in that paper model? Can I use ACDC dataset for 3D medical image segmentation? I don't know about the memory usage.

**Comment by himashi92** [comment]
Hello, I haven't tried the ACDC dataset. However, the model can be used for any 3D dataset for segmentation tasks. To train this model, you need at least a 40GB GPU. You can try reducing the image's batch size and patch size to reduce GPU usage.
