### ISSUE TITLE
Hello author, I would like to ask directly run your code "train_cobionet_semi.py" where to set the percentage of tagged data?

### ISSUE THREAD

**Issue by liaochuanlin** [himashi92/Co-BioNet#6]
Hello author, I would like to ask directly run your code "train_cobionet_semi.py" where to set the percentage of tagged data?

**Comment by liaochuanlin** [comment]
Is "train_cobionet_semi.py" full supervision by default?

**Comment by himashi92** [comment]
Hello, you can set number of labeled samples as in here: https://github.com/himashi92/Co-BioNet/blob/main/code/train_cobionet_semi.py#L37C1-L37C80
