### ISSUE TITLE
Is "train_cobionet_semi.py" full supervision by default?

### ISSUE THREAD

**Issue by liaochuanlin** [himashi92/Co-BioNet#7]
Is "train_cobionet_semi.py" full supervision by default?

**Comment by himashi92** [comment]
No, use this script to train Co-Bionet in supervised setting: https://github.com/himashi92/Co-BioNet/blob/main/code/train_cobionet_sup.py

**Comment by liaochuanlin** [comment]
Thank the author for his reply， The running result of the script code/train_cobionet_sup.py: average metric is 0.7395.

**Comment by himashi92** [comment]
Did you train with the given hyperparameters?

**Comment by smanman** [comment]
@liaochuanlin 请问你复现LA数据集了嘛？复现精度是多少啊
